# Generated by Django 3.2 on 2021-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Makale', 'Makale'), ('İçtihat', 'İçtihat'), ('Güncel Mevzuat', 'Güncel Mevzuat'), ('Haberler', 'Haberler'), ('Diğer', 'Diğer')], default='Diğer', max_length=20),
        ),
    ]
